### ISSUE TITLE
Building for ppc64le

### ISSUE THREAD

**Issue by jchodera** [mdtraj/mdtraj#1432] opened 2019-02-13 05:32 UTC
I'm trying to get `mdtraj` working on [ORNL Summit](https://www.olcf.ornl.gov/summit/), which uses `ppc64le` architecture. 

Building the `_rmsd` extension fails with
```
    building 'mdtraj._rmsd' extension
    creating build/temp.linux-ppc64le-3.7/mdtraj/rmsd
    creating build/temp.linux-ppc64le-3.7/mdtraj/rmsd/src
    $BUILD_PREFIX/bin/powerpc64le-conda_cos7-linux-gnu-cc -DNDEBUG -fwrapv -O2 -Wall -Wstrict-prototypes -mcpu=power8 -mtune=power8 -mpower8-fusion -mpower8-vector -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O3 -pipe -I$PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/mdtraj-1.9.2 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix -DNDEBUG -D_FORTIFY_SOURCE=2 -O3 -fPIC -Imdtraj/rmsd/include -I$PREFIX/lib/python3.7/site-packages/numpy/core/include -I$PREFIX/include/python3.7m -c mdtraj/rmsd/_rmsd.c -o build/temp.linux-ppc64le-3.7/mdtraj/rmsd/_rmsd.o -fopenmp -msse2 -O3 -funroll-loops -Wno-unused-function -Wno-unreachable-code -Wno-sign-compare
    powerpc64le-conda_cos7-linux-gnu-cc: error: unrecognized command line option '-msse2'; did you mean '-misel'?
    error: command '$BUILD_PREFIX/bin/powerpc64le-conda_cos7-linux-gnu-cc' failed with exit status 1
    Running setup.py install for mdtraj: finished with status 'error'
```
Any ideas what should be updated to allow `ppc64le` builds? Presumably, we need to ditch the `-msse2` flags [here](https://github.com/mdtraj/mdtraj/blob/master/setup.py#L167-L169) and [here](https://github.com/mdtraj/mdtraj/blob/master/setup.py#L182-L184) and [here](https://github.com/mdtraj/mdtraj/blob/master/setup.py#L214-L217) on this architecture. Any idea what these should be replaced by, or if other changes might be needed?

**Comment by marscher** [comment] 2019-02-13 11:15
Seems like there is no SSE2 on ppc

Am 13. Februar 2019 06:32:13 MEZ schrieb John Chodera <notifications@github.com>:
>I'm trying to get `mdtraj` working on [ORNL
>Summit](https://www.olcf.ornl.gov/summit/), which uses `ppc64le`
>architecture. 
>
>Building the `_rmsd` extension fails with
>```
>    building 'mdtraj._rmsd' extension
>    creating build/temp.linux-ppc64le-3.7/mdtraj/rmsd
>    creating build/temp.linux-ppc64le-3.7/mdtraj/rmsd/src
>$BUILD_PREFIX/bin/powerpc64le-conda_cos7-linux-gnu-cc -DNDEBUG -fwrapv
>-O2 -Wall -Wstrict-prototypes -mcpu=power8 -mtune=power8
>-mpower8-fusion -mpower8-vector -ftree-vectorize -fPIC
>-fstack-protector-strong -fno-plt -O3 -pipe -I$PREFIX/include
>-fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/mdtraj-1.9.2
>-fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix -DNDEBUG
>-D_FORTIFY_SOURCE=2 -O3 -fPIC -Imdtraj/rmsd/include
>-I$PREFIX/lib/python3.7/site-packages/numpy/core/include
>-I$PREFIX/include/python3.7m -c mdtraj/rmsd/_rmsd.c -o
>build/temp.linux-ppc64le-3.7/mdtraj/rmsd/_rmsd.o -fopenmp -msse2 -O3
>-funroll-loops -Wno-unused-function -Wno-unreachable-code
>-Wno-sign-compare
>powerpc64le-conda_cos7-linux-gnu-cc: error: unrecognized command line
>option '-msse2'; did you mean '-misel'?
>error: command '$BUILD_PREFIX/bin/powerpc64le-conda_cos7-linux-gnu-cc'
>failed with exit status 1
>    Running setup.py install for mdtraj: finished with status 'error'
>```
>Any ideas what should be updated to allow `ppc64le` builds? Presumably,
>we need to ditch the `-msse2` flags
>[here](https://github.com/mdtraj/mdtraj/blob/master/setup.py#L167-L169)
>and
>[here](https://github.com/mdtraj/mdtraj/blob/master/setup.py#L182-L184)
>and
>[here](https://github.com/mdtraj/mdtraj/blob/master/setup.py#L214-L217)
>on this architecture. Any idea what these should be replaced by, or if
>other changes might be needed?

**Comment by rmcgibbo** [comment] 2019-02-13 15:59
A lot of the geometry code uses pretty direct SSE2 and SSE4 intrinsics, as I recall. And Imran's RMSD code is for sure entirely based around explicit SSE2 and SSE3 intrinsics.

**Comment by rmcgibbo** [comment] 2019-02-13 16:09
I guess they have their own incompatible SIMD instructions. Despite the title of the post, I suspect this would be a lot of work to port.

https://developer.ibm.com/linuxonpower/2018/01/24/porting-x86-vector-intrinsics-code-linux-power-hurry/

**Comment by marscher** [comment] 2019-05-16 16:14
duplicate of #888

**Closed by marscher** 2019-05-16 16:14 UTC

**Comment by rmcgibbo** [comment] 2020-06-14 22:02
Based on porting mdtraj to aarch64 (#1562), I suspect this is about a half-day of work for someone with access to a ppc64le machine and knowledge of C/C++ and SIMD intrinsics.

**Comment by tonigi** [comment] 2020-06-15 10:48
I made a non-invasive attempt using the [SIMDE](https://github.com/nemequ/simde) library at https://github.com/giorginolab/mdtraj . It does build, but several key tests fail numerically (puzzlingly). I'm not even sure it's related to intrinsics. As a side note, travis now has ppc64le.

**Comment by DNA2RNA** [comment] 2020-07-07 20:04
For anyone else than needs trajectory analysis on ppc64le, this seemed to work on a Summit-style cluster:

conda create -n PRO python==3.7.6
conda activate PRO
conda install -c bioconda biopython.convert
conda install -c conda-forge scipy
pip install prody

# then log into a node and test:

module load conda
conda activate PRO
python
from prody import *
ensemble = parseDCD('traj_file.dcd')

@> DCD file contains 37 coordinate sets for 53774 atoms.
@> DCD file was parsed in 0.01 seconds.
@> 22.77 MB parsed at input rate 2821.87 MB/s.
@> 37 coordinate sets parsed at input rate 4585 frame/s.

Looks like it only works with dcd files which is fine for my purposes, but could be an issue for others. More info on ProDy here: http://prody.csb.pitt.edu/tutorials/trajectory_analysis/trajectory.html

I hope this helps!

@jchodera @rmcgibbo  @tonigi
