### ISSUE TITLE
load_pdb uses lots of memory (and time)

### ISSUE THREAD

**Issue by rcrehuet** [mdtraj/mdtraj#1172] opened 2016-08-30 14:00 UTC
I was trying to read a multi model PDB. It contains 5000 models  of 2801 atoms each. The file is 896Mb. It is large, but `mdtraj.load_pdb` cannot load it. Ittakes minutes and it uses more than 30Gb of RAM. At the end, I had to kill the process.
Although this is a big file, and PDBs are not good for keeping so many frames, MDAnalysis can read the file in some seconds. 
I can provide the file if you need it.

**Comment by marscher** [comment] 2016-08-30 14:10
I think this is a known problem. However it is a lot of work to tidy this beast up properly.

**Comment by marscher** [comment] 2016-08-30 19:40
eventually duplicate of #395

**Comment by mpharrigan** [comment] 2016-08-30 19:46
Maybe we can use someone else's pdb parsing code. MDAnalysis is GPL but e.g. https://github.com/biopython/biopython/blob/master/Bio/PDB/PDBParser.py is permissive

**Comment by mpharrigan** [comment] 2016-08-30 19:50
Or parmed, cc @swails 

https://github.com/ParmEd/ParmEd/blob/master/parmed/formats/pdb.py

**Comment by rmcgibbo** [comment] 2016-08-30 20:03
I frankly don't think that optimizing the loading of long PDB trajectories is particularly worthwhile. Perhaps others (@marscher?) disagree. PDB is such a poor fit for this use case in the first place.

**Comment by marscher** [comment] 2016-08-30 20:06
On 30.08.2016 22:03, Robert T. McGibbon wrote:
> I frankly don't think that optimizing the loading of long PDB
> trajectories is particularly worthwhile. Perhaps others (@marscher
> <https://github.com/marscher>?) disagree. PDB is such a poor fit for
> this use case in the first place.

I agree, that it is crazy to store that many models in a single file 
(which is non-standard either I'd guess). However the loading speed is 
in general very poor (I added caching for it in PyEMMA, where we load 
topology files a lot).

**Comment by swails** [comment] 2016-08-30 20:44
I agree with lots of people here.  You can try ParmEd, but I wouldn't expect much of a performance boost (if any), although it would likely cut down on RAM usage substantially.  MDTraj treats PDB files more like topologies than trajectories, so it does a lot of work to make sure it extracts all topologically relevant features (the parser was pulled from OpenMM, which reads them exclusively for topology information).

You'd have to get rid of a lot of that functionality to streamline PDB parsing, which comes with its own cost.

There are also many other parsers that operate in seconds -- MDAnalysis (as you pointed out -- taking your word for that one) and pytraj come to mind -- both of which provide data structures that can be easily converted for use in MDTraj if so desired.

It would certainly be nice to streamline parsing, but the priority level is pretty low.  Best advice is use some kind of efficient binary file format to store trajectories.  PDB has so many limitations:

1. Horrible efficiency -- each atom stores 3 low-precision coordinates along with a ton of trajectory-irrelevant data just sucking up space
1. Fixed formatting of the coordinate fields mean you have to compromise precision and at times even fail to represent large coordinates entirely
1. You can only store one set of unit cell vectors, making it misleading for NpT trajectories where unit cell vectors vary from frame to frame
1. Much slower to read
1. Easier to corrupt
1. Small limit on number of residues and atoms, with many (wrong) ways of representing more than 99,999 atoms or 9,999 residues.

Just my thoughts.

**Comment by rcrehuet** [comment] 2016-08-31 10:20
I agree that PDB is not a good format for large trajectories. But it's still widespread in non-MD software, for example NMR software...
Maybe the problem is that the topology is computed for every model, while it should be the same for all models.

**Comment by swails** [comment] 2016-08-31 12:28
> I agree that PDB is not a good format for large trajectories. But it's still widespread in non-MD software, for example NMR software...

Trajectories as large as 800 MB?  NMR structures I've seen are substantially more modest in size (both in terms of number of models and atoms).

> Maybe the problem is that the topology is computed for every model, while it should be the same for all models.

This is certainly *one* of the problems with regards to the OpenMM/MDTraj PDB parser in the context of performance, although hardly the only one.  If MDTraj was implementing its own parser, this assumption would be a good one to implement (and check against) -- but for OpenMM you would arguably *not* want to make this assumption (sure, the standard says it should be that way, but there are far more non-conforming PDBs out there than conforming ones).

However, ParmEd's PDB parser *does* make this assumption, so the topology is stored once and the coordinates stored as a 3-dimensional numpy array with shape `(n_frame, n_atom, 3)`.  It does check that each model has the same atoms in the same order, though, incurring some performance penalty.  But the memory usage should be a lot better.

If you want to try ParmEd, you can use it directly in OpenMM like so (although you need to have both ParmEd and OpenMM installed):

```python
import parmed as pmd
import mdtraj as md

pdb = pmd.load_file('your_trajectory.pdb')
traj = md.Trajectory(pdb.coordinates, md.Topology.from_openmm(pdb.topology))
```

**Closed** 2019-11-26 23:33 UTC
Labels: wontfix
