### ISSUE TITLE
The examples and documentation seem outdated

### ISSUE THREAD

**Issue by davidlmobley** [mdtraj/mdtraj#1122] opened 2016-05-26 23:34 UTC
For example, http://mdtraj.org/latest/viewer.html refers to `from mdtraj.html import TrajectoryView, enable_notebook`, but this fails:

```python

>>> import mdtraj
>>> from mdtraj.html import TrajectoryView, enable_notebook
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name TrajectoryView
```

**Comment by davidlmobley** [comment] 2016-05-26 23:53
This also occurs on various examples in the examples folder, of course. I now see that the appopriate command these days is something more like:

`from mdtraj.html.trajectory_widget import TrajectoryView`

however, it's still not working for me. Troubleshooting.

**Comment by davidlmobley** [comment] 2016-05-27 00:08
It seems like part of my issue was that I must have had an some bits of an old `mdtraj` hanging around in my path, so I've fixed some errors I was getting by wiping that out and doing a clean install. However, I still don't seem to be able to get the viewer widget to work at all. I'm using the latest jupyter notebooks and widgets under python2, but I just get a blank viewer window up, such as using:

```python
traj = mdtraj.load('test.h5')
print(traj)
from mdtraj.html.trajectory_widget import TrajectoryView
from mdtraj.html.install import enable_notebook
enable_notebook()
widget = TrajectoryView(traj, primaryStructure = 'ball & stick', secondaryStructure='ribbon')
widget
```

**Comment by cxhernandez** [comment] 2016-05-27 01:22
Yeah, `mdtraj.html` is not actively being maintained. I'm slowly trying to get things in that module to work using [`nglview`](https://github.com/arose/nglview), but so far I've only been able to replace `TrajectoryView`.

**Comment by davidlmobley** [comment] 2016-05-27 03:28
Ah, that looks helpful. Thanks for the pointer.

On Thu, May 26, 2016 at 6:22 PM, Carlos Hernández <notifications@github.com>
wrote:

> Yeah, mdtraj.html is not actively being maintained. I'm slowly trying to
> get things in that module to work using nglview
> <https://github.com/arose/nglview>, but so far I've only been able to
> replace TrajectoryView.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/mdtraj/mdtraj/issues/1122#issuecomment-222037904>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AGzUYYyxbGBVVF1D89v-okzXd7liWcF8ks5qFkdbgaJpZM4IoDIc>
> .
>



-- 
David Mobley
dmobley@gmail.com
949-385-2436

**Comment by davidlmobley** [comment] 2016-05-30 19:06
Does anyone (@cxhernandez or @hainm maybe) have a super simple example of using `nglview` to visualize a short OpenMM simulation with `mdtraj`? I'm trying to do this but I just get a blank view pane. 

I had previously constructed a simple OpenMM/MDTraj demo for a class which was based on this http://mdtraj.org/latest/examples/openmm.html to run a short simulation and then used the MDTraj TrajectoryViewer to visualize (along the lines of http://mdtraj.org/latest/viewer.html). This is currently broken, so I'm trying to update it to use `nglview` but so far striking out. I'm attaching my notebook.
[Lec17_MDTraj_simulate_and_view.ipynb.zip](https://github.com/mdtraj/mdtraj/files/289993/Lec17_MDTraj_simulate_and_view.ipynb.zip)


My (small) class is tomorrow morning, so I'm soon going to have to make a decision as to whether I need to just teach on something else and ditch the discussion of MDTraj (and use of MDTraj examples, since these no longer seem to be maintained).

**Comment by hainm** [comment] 2016-05-30 19:11
Does below work for you? 

```python
import nglview as nv

view = nv.show_mdtraj(its_trajectory)
view
```

I am using phone now so can't not see your files.

**Comment by hainm** [comment] 2016-05-30 19:13
If that does not work, can you take screenshot of your notebook?

**Comment by davidlmobley** [comment] 2016-05-30 19:50
I do have that.

Screenshots...

Viewer: 
<img width="1095" alt="lec17_mdtraj_simulate_and_view" src="https://cloud.githubusercontent.com/assets/7132257/15657373/096486ac-2665-11e6-9464-00d6258c13a6.png">

Code utilizing OpenMM to generate trajectory: 
<img width="878" alt="lec17_mdtraj_simulate_and_view2" src="https://cloud.githubusercontent.com/assets/7132257/15657375/10b81fae-2665-11e6-8b63-6d97e63fd885.png">

**Comment by hainm** [comment] 2016-05-30 19:53
Ok. I will look further tonight and get back to you as soon as I can.

**Comment by hainm** [comment] 2016-05-30 19:54
Also, can you show output of nglview.__version__?

**Comment by hainm** [comment] 2016-05-30 19:56
'nglview.__version__'

**Comment by hainm** [comment] 2016-05-30 20:08
Ping @arose too

**Comment by davidlmobley** [comment] 2016-05-30 20:11
Well, `nglview.version` seems not to work. But, I just installed today via conda from omnia, and I got:
```
nglview                   0.4                      py27_0    http://conda.binstar.org/omnia/osx-64/nglview-0.4-py27_0.tar.bz2
```

**Comment by hainm** [comment] 2016-05-30 20:18
Please go to nglview github and install development version via pip. 0.4 is quite outdated. (Instruction is there). Make sure to uninstall 0.4 first.

**Comment by davidlmobley** [comment] 2016-05-30 20:43
Well, I'm trying that. Now I get this: `OSError: [Errno 2] No such file or directory: '/Users/dmobley/Library/Jupyter/nbextensions/nglview/'`

Weird.

**Comment by hainm** [comment] 2016-05-30 20:51
Sometimes 'rm -rf /dir/to/installed/nglview/' will do the trick. 

But what do you mean about 'trying that'? 

Hai

**Comment by davidlmobley** [comment] 2016-05-30 21:01
I mean, I just `conda remove`'d the release version, and pip installed the dev version, and ran into the above error. I'll rm -rf the relevant directories and repeat.

**Comment by hainm** [comment] 2016-05-30 21:03
Uhm, i am not clear which step you got error, remove or install?

**Comment by davidlmobley** [comment] 2016-05-30 21:04
The error is when I attempt to use it. Removing and installing went fine.

**Comment by hainm** [comment] 2016-05-30 21:14
Uhm, weird. In my mac, the nbextension will be installed in $HOME/.local/share/jupyter/

Hai

**Comment by davidlmobley** [comment] 2016-05-30 21:16
OK, so I removed everything relating to nglview I could find and did a clean reinstall of the development version using pip as directed. Now, I don't get any errors. However, I also no longer get a viewer window at all, so I can't see anything with `nglview`.

To rule out problems with my files, I tried inputting the demo from https://github.com/arose/nglview directly into an Ipython notebook:
```python
import nglview as nv
import pytraj as pt

traj = pt.load(nv.datafiles.TRR, nv.datafiles.PDB)
view= nv.show_pytraj(traj)
view
```
However, unlike as noted on the nglview docs, I don't get any image coming up, here.

**Comment by hainm** [comment] 2016-05-30 21:23
Sorry for those issues you met. I only tested nglview with Chrome on osx. Are you using safari? Btw, i am sure will look those tonight.

**Comment by davidlmobley** [comment] 2016-05-30 21:24
I'm on Chrome on OS X under python2.7.

**Comment by hainm** [comment] 2016-05-30 23:15
I can not reproduce your issue. :( 

This is what I did

- delete all things related to `nglview` (to make sure `python -c 'import nglview'` does NOT work)

- create `test_mdtraj_nglview` env
```bash
conda create -n test_mdtraj_nglview python=2.7 numpy jupyter notebook
source activate test_mdtraj_nglview
conda install mdtraj openmm -c omnia
python -m pip install git+https://github.com/arose/nglview
python -c 'import nglview; print(nglview)
jupyter notebook Lec17_MDTraj_simulate_and_view.ipynb
```

Note: I could not run your whole notebook since I got `ValueError` saying `test.h5` is already opened.
so I just ran `openmm` first to get `test.h5`, closed my notebook, run 2nd cell (with minor modification) to reload `test.h5`.

This is what I saw:
![mdtraj_nglview](https://cloud.githubusercontent.com/assets/4451957/15659575/ac906a1e-269a-11e6-8b4c-7eb57282d0fb.png)


Those are all pakages in my envs:

```bash
~/tests/test_mdtraj_nglview $ conda list
# packages in environment at /Users/haichit/miniconda/envs/test_mdtraj_nglview:
#
amberlite                 16.0                      <pip>
ambertools                16.0                      <pip>
appnope                   0.1.0                    py27_0    defaults
backports                 1.0                      py27_0    defaults
backports-abc             0.4                       <pip>
backports.shutil-get-terminal-size 1.0.0                     <pip>
backports.ssl-match-hostname 3.4.0.2                   <pip>
backports_abc             0.4                      py27_0    defaults
configparser              3.5.0b2                  py27_1    defaults
decorator                 4.0.9                    py27_0    defaults
entrypoints               0.2                      py27_1    defaults
fftw3f                    3.3.4                         2    omnia
freetype                  2.5.5                         0    defaults
functools32               3.2.3.2                  py27_0    defaults
get_terminal_size         1.0.0                    py27_0    defaults
hdf5                      1.8.16                        0    defaults
ipykernel                 4.3.1                    py27_0    defaults
ipython                   4.2.0                    py27_1    defaults
ipython-genutils          0.1.0                     <pip>
ipython_genutils          0.1.0                    py27_0    defaults
ipywidgets                4.1.1                    py27_0    defaults
jinja2                    2.8                      py27_1    defaults
jsonschema                2.5.1                    py27_0    defaults
jupyter                   1.0.0                    py27_2    defaults
jupyter-client            4.2.2                     <pip>
jupyter-console           4.1.1                     <pip>
jupyter-core              4.1.0                     <pip>
jupyter_client            4.2.2                    py27_0    defaults
jupyter_console           4.1.1                    py27_0    defaults
jupyter_core              4.1.0                    py27_0    defaults
libpng                    1.6.17                        0    defaults
markupsafe                0.23                     py27_2    defaults
mdtraj                    1.7.2               np111py27_0    omnia
mistune                   0.7.2                    py27_1    defaults
mkl                       11.3.3                        0    defaults
mmpbsa.py                 16.0                      <pip>
nbconvert                 4.2.0                    py27_0    defaults
nbformat                  4.0.1                    py27_0    defaults
nglview                   0.4+189.g09d0cb3           <pip>
nose                      1.3.7                    py27_1    defaults
notebook                  4.2.0                    py27_0    defaults
numexpr                   2.5.2               np111py27_1    defaults
numpy                     1.11.0                   py27_1    defaults
openmm                    7.0rc1                   py27_1    omnia
openssl                   1.0.2h                        0    defaults
pandas                    0.18.1              np111py27_0    defaults
parmed                    0.1.2.dev4+46324.gfe7831d.dirty           <pip>
path.py                   8.2.1                    py27_0    defaults
pexpect                   4.0.1                    py27_0    defaults
pickleshare               0.5                      py27_0    defaults
pip                       8.1.1                    py27_1    defaults
ptyprocess                0.5                      py27_0    defaults
pygments                  2.1.3                    py27_0    defaults
pymsmt                    16.0                      <pip>
pyqt                      4.11.4                   py27_1    defaults
pytables                  3.2.2               np111py27_3    defaults
python                    2.7.11                        0    defaults
python-dateutil           2.5.3                    py27_0    defaults
python.app                1.2                      py27_4    defaults
pytraj                    1.0.6.dev0+unknown           <pip>
pytz                      2016.4                   py27_0    defaults
pyzmq                     15.2.0                   py27_1    defaults
qt                        4.8.7                         1    defaults
qtconsole                 4.2.1                    py27_0    defaults
readline                  6.2                           2    defaults
sander                    16.0                      <pip>
scipy                     0.17.1              np111py27_0    defaults
setuptools                21.2.1                   py27_0    defaults
simplegeneric             0.8.1                    py27_0    defaults
singledispatch            3.4.0.3                  py27_0    defaults
sip                       4.16.9                   py27_0    defaults
six                       1.10.0                   py27_0    defaults
sqlite                    3.13.0                        0    defaults
ssl_match_hostname        3.4.0.2                  py27_1    defaults
tables                    3.2.2                     <pip>
terminado                 0.5                      py27_1    defaults
tk                        8.5.18                        0    defaults
tornado                   4.3                      py27_1    defaults
traitlets                 4.2.1                    py27_0    defaults
wheel                     0.29.0                   py27_0    defaults
zlib                      1.2.8                         3    defaults
```

**Comment by hainm** [comment] 2016-05-30 23:18
Please pay attention to those first (all relate to Jupyter project, version 4)

```bash
ipykernel                 4.3.1                    py27_0    defaults
ipython                   4.2.0                    py27_1    defaults
ipywidgets                4.1.1                    py27_0    defaults
jupyter                   1.0.0                    py27_2    defaults
jupyter-client            4.2.2                     <pip>
jupyter-console           4.1.1                     <pip>
jupyter-core              4.1.0                     <pip>
jupyter_client            4.2.2                    py27_0    defaults
jupyter_console           4.1.1                    py27_0    defaults
jupyter_core              4.1.0                    py27_0    defaults
notebook                  4.2.0                    py27_0    defaults
```

My wild guess is that you have `ipywidgets >= 5.0` in somewhere. (but `nglview` does force user to downgrade to version 4).

**Comment by hainm** [comment] 2016-05-30 23:20
my Chrome `Version 50.0.2661.102 (64-bit)`

**Comment by hainm** [comment] 2016-05-30 23:23
if you still can not reproduce what I saw, please follow below

- open your notebook
- run it
- wait for few seconds to see if the `widgets` displayed
- if not, right click your mouse (outside Cell), choose `Inspect`, then choose `Console` (top right of your screen). Post what you saw in that Console here.

**Comment by hainm** [comment] 2016-05-31 06:16
phew, I think I know what's going on. I accidentally did not include all javascripts files during installation.

The fix is here: https://github.com/arose/nglview/commit/286d8aaee40251eb5c130297f405db5b99df2448

can you try again
`python -m pip install git+https://github.com/arose/nglview`

should work properly.

You should see something similar to below

```
$ ls /u1/haichit/anaconda3/lib/python3.5/site-packages/nglview/js/
chroma.min.js  mmtf-decode.js     ngl.js               promise.min.js  signals.min.js  
svd.min.js           TypedFastBitSet.js
__init__.py    msgpack-decode.js  pako_inflate.min.js 
 __pycache__     sprintf.min.js  three.custom.min.js  widget_ngl.js
```

**Comment by hainm** [comment] 2016-05-31 06:17
I also have a live [mybinder notebook for mdtraj and others](mybinder.org/repo/hainm/nglview-notebooks) here.

**Comment by davidlmobley** [comment] 2016-05-31 21:05
I just installed again and have the js files. However, I'm still getting no response from the viewer. I wonder if it's a python2.7 issue? I see you're running 3.5. 

I will, I suppose, attempt setting up a separate conda environment and installing from scratch in a clean environment as you suggest to see if that works.

**Comment by hainm** [comment] 2016-05-31 21:11
I tried with py2.7 (please see my previous post) and I could see the viewer.

`conda create -n test_mdtraj_nglview python=2.7 numpy jupyter notebook`

> I will, I suppose, attempt setting up a separate conda environment and installing from scratch in a clean environment as you suggest to see if that works. 

Yes, please try to copy and paste my commands.

**Comment by davidlmobley** [comment] 2016-05-31 21:58
OK, thanks. That means I've gotten it working in the test environment. 

Do you have any suggestions on how to troubleshoot my normal environment, then?

**Comment by davidlmobley** [comment] 2016-05-31 21:59
Sorry, in case it wasn't clear from what I just wrote (my brain didn't connect to my fingers apparently) - I followed your instructions and I now have the viewer working in a notebook in the test environment as per your instructions. Thanks for that. Now I'm only trying to figure out where to go from here - i.e. it works in this environment, so how do I fix my normal environment? I'm new to the env's in conda, having only dealt with them maybe once before.

**Comment by hainm** [comment] 2016-05-31 21:59
> That means I've gotten it working in the test environment. 

 Do you make it work for your test env?

**Comment by hainm** [comment] 2016-05-31 21:59
nvm. Just read you updated post.

**Comment by hainm** [comment] 2016-05-31 22:01
In your normal env, can you post  here the output of

```bash
conda list
```

send me email (hainm.comp gmail.com) if you don't want to post here.

**Comment by hainm** [comment] 2016-05-31 22:03
and `pip list` too.

**Comment by davidlmobley** [comment] 2016-05-31 22:04
Yes.

**Comment by hainm** [comment] 2016-05-31 22:14
Just got yours.  I will check and get back to you later.

**Comment by davidlmobley** [comment] 2016-05-31 22:21
OK, so hold on on your troubleshooting. After deactivating the testing environment and trying again, it appears to be working for me now. I'm wondering if I was working in a window in which I'd forgotten to source my .bash_profile between installing things or something. 

But anyway - at the moment I seem to have it working with the environment details I just sent you, which suggests you may not need to do anything else. I'll keep working on it and get back to you if I have any more problems. Thanks!

**Comment by hainm** [comment] 2016-05-31 22:25
> But anyway - at the moment I seem to have it working with the environment details I just sent you, which suggests you may not need to do anything else. I'll keep working on it and get back to you if I have any more problems. Thanks!

 fantastic. Feel free to open any issue in [nglview page](https://github.com/arose/nglview/issues) so we can keep track.

> after deactivating the testing environment and trying again, it appears to be working for me now.

I think while testing on test env, `nglview` copied `*.js` files to `$HOME/.local/share/jupyter/...` 
or `$HOME/.jupyter...`. When you switch env, those files are still there (which is good since you are using correct files).

**Comment by peastman** [comment] 2016-06-08 19:04
I have something working that loads all the notebooks in the examples folder as tests, reporting an error if any cell throws an exception.  The good news is that WebGL-Viewer.ipynb is the only one that fails.  What should I do about that one?  If it uses classes that are no longer being maintained, should I just delete that notebook?

**Comment by mpharrigan** [comment] 2016-06-08 19:12
cc @cxhernandez who said he'd take the lead on moving away from supporting our own gl viewer

**Comment by davidlmobley** [comment] 2016-06-08 19:15
Yes, I have a modified version that works with nglview, so that seems to be
a good solution, especially if someone is going to support.

DM


On Wed, Jun 8, 2016 at 12:12 PM, Matthew Harrigan <notifications@github.com>
wrote:

> cc @cxhernandez <https://github.com/cxhernandez> who said he'd take the
> lead on moving away from supporting our own gl viewer
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/mdtraj/mdtraj/issues/1122#issuecomment-224697071>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AGzUYaPVoqflsF-Ui86bm98ABq-Cc18Cks5qJxQtgaJpZM4IoDIc>
> .
>



-- 
David Mobley
dmobley@gmail.com
949-385-2436

**Comment by cxhernandez** [comment] 2016-06-08 19:17
@peastman: Is there a way to exclude it as a test for now? Eventually, I'll try to get that notebook to work with nglview.

**Comment by peastman** [comment] 2016-06-08 19:20
If you have a version that works, go ahead and send a PR replacing the broken version.

**Comment by peastman** [comment] 2016-06-08 19:35
I'm not sure how to integrate my test with travis and appveyor.  It loops over every file in the examples directory and tests each one.  But the examples don't get installed.  They're strictly part of the source.  And tests don't get run against the source tree.  Instead, the module gets installed into a temporary environment and testing is done there.  Any advice on how I can do this?

**Comment by davidlmobley** [comment] 2016-06-08 19:43
Can you make a test function that travis DOES run that runs your test?

On Wed, Jun 8, 2016 at 12:35 PM, peastman <notifications@github.com> wrote:

> I'm not sure how to integrate my test with travis and appveyor. It loops
> over every file in the examples directory and tests each one. But the
> examples don't get installed. They're strictly part of the source. And
> tests don't get run against the source tree. Instead, the module gets
> installed into a temporary environment and testing is done there. Any
> advice on how I can do this?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/mdtraj/mdtraj/issues/1122#issuecomment-224703015>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AGzUYY1AK7RWj79m-rDXToGGhZVrqYkgks5qJxlugaJpZM4IoDIc>
> .
>



-- 
David Mobley
dmobley@gmail.com
949-385-2436

**Comment by davidlmobley** [comment] 2016-06-08 19:44
> If you have a version that works, go ahead and send a PR replacing the
broken version.

Mine is actually somewhat modified/extended/revised for a class. Maybe I
can just send the notebook or excerpt it here and one of you can do it?
(Sorry, swamped right now).

On Wed, Jun 8, 2016 at 12:20 PM, peastman <notifications@github.com> wrote:

> If you have a version that works, go ahead and send a PR replacing the
> broken version.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/mdtraj/mdtraj/issues/1122#issuecomment-224699228>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AGzUYY1sEM6oC9ByfN8mtW_ZCPUpkJtgks5qJxYTgaJpZM4IoDIc>
> .
>



-- 
David Mobley
dmobley@gmail.com
949-385-2436

**Comment by hainm** [comment] 2016-06-08 19:50
testing graphics is a it complicated. You need to create a web server, open the notebook, run it and capture screen to make sure it really works (even if there is no exception). Below is what we did for NGLView:

https://github.com/hainm/nbtests

**Comment by peastman** [comment] 2016-06-08 20:02
> Can you make a test function that travis DOES run that runs your test?

Getting it to run the test isn't the problem.  But the test just loops over every file in the examples directory, and it won't have access to that directory in the conda environment where tests get run.

**Comment by peastman** [comment] 2016-06-08 20:03
I'm not trying to test that the graphics are correct or anything like that.  Just that it can execute every cell in the notebook and nothing throws an exception.

**Comment by mpharrigan** [comment] 2016-06-08 22:24
`conda build` defined the environment variable `SRC_DIR`. In the `meta.yaml` file you can add a new test that can be an arbitrary command or bash script. You can `cd` to `SRC_DIR` and run your script. This is all done in the temporary conda environment where mdtraj is installed

**Comment by mpharrigan** [comment] 2016-06-08 22:24
http://conda.pydata.org/docs/building/environment-vars.html

**Closed** 2016-06-20 21:28 UTC
