### ISSUE TITLE
Select chain by letters

### ISSUE THREAD

**Issue by tomnewport** [mdtraj/mdtraj#1240] opened 2017-03-02 11:56 UTC
I'd like to be able to access the chain lettering from a PDB file using mdtraj - I can see a chainID and a segmentID in the dataframe, but chainID is a numeric index and segmentID seems to be empty.

Trajectory.topology.chains also gives access to the chains, but there doesn't seem to be a way to access the letters.

**Comment by tomnewport** [comment] 2017-05-02 14:27
![giphy](https://cloud.githubusercontent.com/assets/8523691/25622260/c5292c90-2f4b-11e7-9f5b-3f97c9cf93cf.gif)

**Comment by rmcgibbo** [comment] 2017-05-02 14:42
Sorry, the chain letters aren't loaded.

**Comment by tomnewport** [comment] 2017-05-02 14:45
Thanks for getting back to me! Are there plans to load chain letters? We're figuring out whether to switch from MDAnalysis to mdtraj for Python3 support and this is one of the features we need.

**Comment by rmcgibbo** [comment] 2017-05-02 15:01
If you want to add it, pull requests are always welcome. Otherwise no, I don't think that's something that's on anyone else's agenda.

**Comment by mpharrigan** [comment] 2017-05-02 18:19
cc #1073 #1081 #876 #873

**Comment by ajasja** [comment] 2017-06-16 21:12
Yup this is a duplicate of #873. Would definitely be nice to have.

**Closed** 2019-11-26 22:32 UTC
Labels: wontfix
