### ISSUE TITLE
Release 1.9

### ISSUE THREAD

**Issue by cxhernandez** [mdtraj/mdtraj#1251] opened 2017-04-10 23:44 UTC
This seems somewhat overdue. Tag release blockers with 1.9 milestone

**Comment by mpharrigan** [comment] 2017-04-10 23:53
https://github.com/mdtraj/mdtraj/issues/1249 and duplicates https://github.com/mdtraj/mdtraj/issues/1234 https://github.com/mdtraj/mdtraj/issues/1212

**Comment by mpharrigan** [comment] 2017-04-10 23:55
Here's a list of merged PRs

Listing merged PRs since: MDTraj 1.8

PR #1247: added diffrentialable contacts option
PR #1237: Remove link to forum
PR #1238: Skip renumbering if no bonds in mol2
PR #1174: Added a bunch of Van Der Waals values for all the elements that have
PR #1233: [geometry] fix compatibility with old visual studio for Python 2.7
PR #1221: Implemented compute_average_structure()
PR #1231: Update `__init__.py`
PR #1227: Fix bugs in load with atom_indices and frame args
PR #1228: Fix conda test running
PR #1223: Amber restart file convention
PR #1208: Install path for zlib on linux (too)

**Comment by mpharrigan** [comment] 2017-04-10 23:57
Also a todo: remove all the patches from the 1.8 conda binaries https://github.com/conda-forge/mdtraj-feedstock

**Comment by mpharrigan** [comment] 2017-09-04 01:06
updated list:

merged PRs:

PR #1265: [xtc] approx_nframes returns at least one.
PR #1260: Make compute_directors() user-facing
PR #1258: Remove "lib" from .gitignore
PR #1247: added diffrentialable contacts option
PR #1237: Remove link to forum
PR #1238: Skip renumbering if no bonds in mol2
PR #1174: Added a bunch of Van Der Waals values for all the elements that have
PR #1233: [geometry] fix compatibility with old visual studio for Python 2.7
PR #1221: Implemented compute_average_structure()
PR #1231: Update __init__.py
PR #1227: Fix bugs in load with atom_indices and frame args
PR #1228: Fix conda test running
PR #1223: Amber restart file convention
PR #1208: Install path for zlib on linux (too)

Squash/rebase PRs (don't show up using `gh-util list-prs` solution in devtools/readme

Fix tranform calculation and Transform object to be more general. #1254
Fix #1256: Add O1 as alternative definition for water oxygen. #1257
Fix precentering overflow error in center.c (#1283)
added chi5 angle computation (#1291)
Fix the build bug caused by incorrect plumbing the `numpy include path` into the cflags #1290
Make RDF `pairs` argument required #1288
Refresh tests (#1266)
Remove PyPI downloads badge (#1293)
Extracting velocities/forces from TRR files (hidden API) - Rebase #1294
Add "in" selection to selection language #1268
Handle a single frame being passed to sparta+ - Rebase (#1295)


Side note: for future PRs, we should (1) make sure they have good titles. (2) merge using the squash option which lovingly puts the PR number in the singular commit. Then for release notes we can use the "commits since this release" feature of github

**Comment by mpharrigan** [comment] 2017-09-04 01:06
I'm going to cut a release soon unless someone has a pressing concern

**Comment by mpharrigan** [comment] 2017-09-04 02:47
- [x] version tagged
- [x] docs updated
- [x] sdist on pypi
- [ ] conda-forge https://github.com/conda-forge/mdtraj-feedstock/pull/13
- [ ] omnia 

If someone's interested in spearheading wheel upload (cc #1277 ) let me know. Otherwise I'm not going to do it

**Comment by mpharrigan** [comment] 2017-09-04 02:48
p.s. the next version will be 2.0, not 1.10 because 1.10 looks like the number 1.10 which is less than 1.9. We should still aim for backwards compatibility

**Closed** 2017-09-05 19:03 UTC
