### ISSUE TITLE
mdtraj 1.9.5 selection issue

### ISSUE THREAD

**Issue by wlsong** [mdtraj/mdtraj#1650] opened 2021-05-18 14:57 UTC
Hi, 

I upgraded mdtraj to 1.9.5 then realised the selection function is no longer working. I tried to selection molecules named as "CHOL" using traj.top.select, then the following error occurred. I wonder if anyone has some insights on how to fix this issue please. Thanks. 

Wanling

In [11]: traj.top.select("resname CHOL")
Traceback (most recent call last):

  File "<ipython-input-11-4bdc805eeedd>", line 1, in <module>
    traj.top.select("resname CHOL")

  File "/Users/wlsong/opt/anaconda3/lib/python3.8/site-packages/mdtraj/core/topology.py", line 1056, in select
    filter_func = parse_selection(selection_string).expr

  File "/Users/wlsong/opt/anaconda3/lib/python3.8/site-packages/mdtraj/core/selection.py", line 399, in __call__
    source = astunparse.unparse(astnode)

  File "/Users/wlsong/opt/anaconda3/lib/python3.8/site-packages/astunparse/__init__.py", line 13, in unparse
    Unparser(tree, file=v)

  File "/Users/wlsong/opt/anaconda3/lib/python3.8/site-packages/astunparse/unparser.py", line 38, in __init__
    self.dispatch(tree)

  File "/Users/wlsong/opt/anaconda3/lib/python3.8/site-packages/astunparse/unparser.py", line 66, in dispatch
    meth(tree)

  File "/Users/wlsong/opt/anaconda3/lib/python3.8/site-packages/astunparse/unparser.py", line 696, in _Compare
    self.dispatch(e)

  File "/Users/wlsong/opt/anaconda3/lib/python3.8/site-packages/astunparse/unparser.py", line 66, in dispatch
    meth(tree)

  File "/Users/wlsong/opt/anaconda3/lib/python3.8/site-packages/astunparse/unparser.py", line 551, in _Constant
    if t.kind == "u":

AttributeError: 'Constant' object has no attribute 'kind'

**Comment by rmcgibbo** [comment] 2021-05-18 16:00
There are other tickets about this. It's been fixed on the master branch, and you can also downgrade astunparse.

**Comment by rmcgibbo** [comment] 2021-05-18 16:01
Duplicate of #1613. See the linked tickets there for more information.

**Closed by rmcgibbo** 2021-05-18 16:01 UTC
