### ISSUE TITLE
Incorrect PDB atom indices

### ISSUE THREAD

**Issue by SimonBoothroyd** [mdtraj/mdtraj#1611] opened 2021-01-07 10:32 UTC
## Description

It seems that `1.9.5` changed the way that the indices of atoms are [written to PDB files ](https://github.com/mdtraj/mdtraj/pull/1584). This seems to have introduced several issues.

### Round-tripping PDB without TER statements

Loading a PDB file which does not contain TER statements and re-saving out the loaded structure will lead to a PDB file with atom indices which do not take into account the newly added TER statements. 

This can be reproduced by loading and then re-saving the following PDB

```
ATOM      1  O1  HOH A   1       4.012   4.851   0.586  1.00  0.00           O
ATOM      2  H1  HOH A   1       4.826   4.387   0.302  1.00  0.00           H
ATOM      3  H2  HOH A   1       3.243   4.622   0.021  1.00  0.00           H
ATOM      4  C1  MOL B   1       3.024   3.160   3.102  1.00  0.00           C
ATOM      5  O1  MOL B   1       4.131   3.989   3.088  1.00  0.00           O
ATOM      6  H1  MOL B   1       2.484   3.163   4.060  1.00  0.00           H
ATOM      7  H2  MOL B   1       3.406   2.119   2.930  1.00  0.00           H
ATOM      8  H3  MOL B   1       2.305   3.360   2.302  1.00  0.00           H
ATOM      9  H4  MOL B   1       3.955   4.912   3.354  1.00  0.00           H
CONECT    4    5    6    7    8
CONECT    5    4    9
CONECT    6    4
CONECT    7    4
CONECT    8    4
CONECT    9    5
END
```

according to:

```
traj_1 = mdtraj.load("input.pdb")
print([(bond.atom1.index, bond.atom2.index) for bond in traj_1.topology.bonds])

>>> [(0, 1), (0, 2), (3, 4), (3, 5), (3, 6), (3, 7), (4, 8)]

traj_1.save_pdb("output.pdb")

traj_2 = mdtraj.load("output.pdb")
print([(bond.atom1.index, bond.atom2.index) for bond in traj_2.topology.bonds])

>>> [(0, 1), (0, 2), (4, 5), (4, 6), (4, 7), (4, 8)]

```

The mis-indexing of the PDB file then also leads to the bonds in the molecule being incorrectly interpreted as highlighted by the above snippet.

`output.pdb`:

```
MODEL        0
ATOM      1  O   HOH A   1       4.012   4.851   0.586  1.00  0.00           O  
ATOM      2  H1  HOH A   1       4.826   4.387   0.302  1.00  0.00           H  
ATOM      3  H2  HOH A   1       3.243   4.622   0.021  1.00  0.00           H  
TER       4      HOH A   1
ATOM      4  C1  MOL B   1       3.024   3.160   3.102  1.00  0.00           C  
ATOM      5  O1  MOL B   1       4.131   3.989   3.088  1.00  0.00           O  
ATOM      6  H1  MOL B   1       2.484   3.163   4.060  1.00  0.00           H  
ATOM      7  H2  MOL B   1       3.406   2.119   2.930  1.00  0.00           H  
ATOM      8  H3  MOL B   1       2.305   3.360   2.302  1.00  0.00           H  
ATOM      9  H4  MOL B   1       3.955   4.912   3.354  1.00  0.00           H  
TER      10      MOL B   1
ENDMDL
CONECT    5    6    7    8    9
CONECT    6    5   10
CONECT    7    5
CONECT    8    5
CONECT    9    5
CONECT   10    6
END
```

### Joining topologies

A similar issue also seems to occur when joining two topologies:

```
trajectory1: mdtraj.Trajectory = mdtraj.load_pdb("topo-1.pdb")
trajectory2: mdtraj.Trajectory = mdtraj.load_pdb("topo-2.pdb")

joined_topology = trajectory1.topology.join(trajectory2.topology)
joined_trajectory = mdtraj.Trajectory(
    numpy.hstack([trajectory1.xyz, trajectory2.xyz]), joined_topology
)
print([(bond.atom1.index, bond.atom2.index) for bond in joined_topology.bonds])

>>> [(0, 1), (0, 2), (3, 4), (3, 5), (3, 6), (3, 7), (4, 8)]

joined_trajectory.save_pdb("joined.pdb")

traj_2 = mdtraj.load("joined.pdb")
print([(bond.atom1.index, bond.atom2.index) for bond in traj_2.topology.bonds])

>>> [(0, 1), (0, 2), (7, 8)]
```

where `topo-1.pdb` looks like:

```
MODEL        0
ATOM      1  O1  HOH A   1      -0.001   0.366  -0.000  1.00  0.00           O
ATOM      2  H1  HOH A   1      -0.812  -0.183  -0.000  1.00  0.00           H
ATOM      3  H2  HOH A   1       0.813  -0.183   0.000  1.00  0.00           H
TER       4      HOH A   1
ENDMDL
END
```

and `topo-2.pdb` looks like:

```
MODEL        0
ATOM      1  C1  MOL A   1      -0.351  -0.005  -0.018  1.00  0.00           C  
ATOM      2  O1  MOL A   1       0.964  -0.362  -0.260  1.00  0.00           O  
ATOM      3  H1  MOL A   1      -0.598   0.062   1.052  1.00  0.00           H  
ATOM      4  H2  MOL A   1      -0.986  -0.816  -0.463  1.00  0.00           H  
ATOM      5  H3  MOL A   1      -0.658   0.927  -0.501  1.00  0.00           H  
ATOM      6  H4  MOL A   1       1.629   0.195   0.189  1.00  0.00           H  
TER       7      MOL A   1
ENDMDL
CONECT    1    2    3    4    5
CONECT    2    1    6
CONECT    3    1
CONECT    4    1
CONECT    5    1
CONECT    6    2
END
```

**Comment by rmcgibbo** [comment] 2021-01-07 16:05
Maybe related to #1584. Can you try reverting that commit?

**Comment by rmcgibbo** [comment] 2021-01-07 16:36
Perhaps you and @sroet could come to an agreement about the desired behavior here.

**Comment by sroet** [comment] 2021-01-07 18:13
Hey, I am sorry about this regression, and thank you for having nice examples.

Do you mind checking if #1612 solves your issues?

The reason I went for that option is that for more than 1 chain we can't guarantee that the atom.serial makes sense after saves, as demonstrated by your example, but I would like to keep some of the functionality in order to still resolve #1583 for the trivial case of only 1 chain in the topology

**Comment by mattwthompson** [comment] 2021-07-08 02:01
#1612 has been merged and included in a release - I vaguely recall it fixes this?

**Closed** 2022-04-16 06:32 UTC
Labels: wontfix
