### ISSUE TITLE
mdtraj.compute_contact issue with sidechain.

### ISSUE THREAD

**Issue by matteo-cagiada** [mdtraj/mdtraj#1580] opened 2020-09-18 11:48 UTC
Hi I have a problem with running mdtraj.compute_contacts on my pdb files. I am using the code to run over CA atoms and I don't get any errors, but if I try to use the schemes sidechain/sidechain-heavy I get a: 'zero-size array to reduction operation minimum which has no identity' error. 
The code that I am using is this:
` pdb=md.load('../pdb/pdb5lpg.pdb')
    topology = pdb.topology
    chainA = topology.select('chainid 0 and protein')
    pdb_chain0 = pdb.atom_slice(chainA)
    print(pdb_chain0)
    pdb_dist,pdb_rp=md.compute_contacts(pdb_chain0, scheme='sidechain', periodic=False)`

and it gives me back the following error:

`ValueError                                Traceback (most recent call last)
<ipython-input-161-6523cfbfde38> in <module>
----> 1 NUDT15_cm=load_cm(NUDT15_pdb)
<ipython-input-160-1efb01cf1056> in load_cm(pdb)
      4     pdb_chain0 = pdb.atom_slice(chainA)
      5     print(pdb_chain0)
----> 6     pdb_dist,pdb_rp=md.compute_contacts(pdb_chain0, scheme='sidechain', periodic=False)
      7     pdb_cm=md.geometry.squareform(pdb_dist,pdb_rp)[0]
      8     return pdb_cm
~/opt/anaconda3/lib/python3.7/site-packages/mdtraj/geometry/contact.py in compute_contacts(traj, contacts, scheme, ignore_nonprotein, periodic, soft_min, soft_min_beta)
    217             n = n_atom_pairs_per_residue_pair[i]
    218             if not soft_min:
--> 219                 distances[:, i] = atom_distances[:, index : index + n].min(axis=1)
    220             else:
    221                 distances[:, i] = soft_min_beta / \
~/opt/anaconda3/lib/python3.7/site-packages/numpy/core/_methods.py in _amin(a, axis, out, keepdims, initial, where)
     32 def _amin(a, axis=None, out=None, keepdims=False,
     33           initial=_NoValue, where=True):
---> 34     return umr_minimum(a, axis, None, out, keepdims, initial, where)
     35 
     36 def _sum(a, axis=None, dtype=None, out=None, keepdims=False,
ValueError: zero-size array to reduction operation minimum which has no identity`

I tried with different pdbs(i.e. 5lpg,1d5r..) and I didn't find any combination of commands to solve the problem. Do you have any idea on how to solve this?

**Comment by proteins247** [comment] 2021-04-03 18:16
Hypothesis: I believe the issue is because of glycines. There are no heavy atoms in the Gly sidechain, so it leads to an error.

**Comment by rmcgibbo** [comment] 2021-10-12 14:47
I think this is now fixed in master.

**Closed by rmcgibbo** 2021-10-12 14:47 UTC
Labels: wontfix
