### ISSUE TITLE
mol2 bond status bits not supported

### ISSUE THREAD

**Issue by pfrstg** [mdtraj/mdtraj#777] opened 2015-03-23 23:50 UTC
I can't submit the original file that created this problem, but I create a problematic file.

mol2 bond records have optional status bits associated with a bond
See page 13 of 
http://www.tripos.com/data/support/mol2.pdf

In my case, this showed up as
bond line like:
      3    2   15 am   BACKBONE|DICT|INTERRES
 
I looked a little at fixing this, but because this uses pandas read_table, it's not trivial. I could filter out the status bits with some simple regexping but I wanted to discuss here what the best way to fix this would be.

**Comment by pfrstg** [comment] 2015-03-23 23:51
(I don't see how to attach a file to an issue, but here's a hacked version of 
lysozyme-ligand-tripos.mol2 (from testing/reference)

@<TRIPOS>MOLECULE
*****
   18    18     0     0     0
SMALL
NO_CHARGES

@<TRIPOS>ATOM
      1 C1         41.2490   44.5850   18.4770 C.ar      1 TMP1        0.0000
      2 C2         41.7650   45.4480   19.4520 C.ar      1 TMP1        0.0000
      3 C3         41.8040   44.5680   17.1930 C.ar      1 TMP1        0.0000
      4 C4         40.0930   43.6730   18.8120 C.3       1 TMP1        0.0000
      5 C5         42.8370   46.2930   19.1410 C.ar      1 TMP1        0.0000
      6 C6         42.8760   45.4140   16.8820 C.ar      1 TMP1        0.0000
      7 C7         43.3920   46.2760   17.8570 C.ar      1 TMP1        0.0000
      8 C8         44.5480   47.1880   17.5220 C.3       1 TMP1        0.0000
      9 H1         41.3440   45.4610   20.4260 H         1 TMP1        0.0000
     10 H2         41.4130   43.9140   16.4530 H         1 TMP1        0.0000
     11 H3         40.3170   42.6530   18.4650 H         1 TMP1        0.0000
     12 H4         39.9380   43.6640   19.9020 H         1 TMP1        0.0000
     13 H5         39.1820   44.0380   18.3140 H         1 TMP1        0.0000
     14 H6         43.2290   46.9470   19.8810 H         1 TMP1        0.0000
     15 H7         43.2970   45.4010   15.9080 H         1 TMP1        0.0000
     16 H8         45.3340   46.6120   17.0120 H         1 TMP1        0.0000
     17 H9         44.1990   47.9960   16.8610 H         1 TMP1        0.0000
     18 H10        44.9540   47.6210   18.4480 H         1 TMP1        0.0000
@<TRIPOS>BOND
     1    6   15 1
     2    3   10 1   BACKBONE|DICT|INTERRES
     3    8   17 1
     4    3    6 ar
     5    6    7 ar
     6    8   16 1
     7    1    3 ar
     8    7    8 1
     9    8   18 1
    10    5    7 ar
    11    4   13 1
    12    4   11 1
    13    1    4 1
    14    1    2 ar
    15    4   12 1
    16    2    5 ar
    17    5   14 1
    18    2    9 1

**Comment by rmcgibbo** [comment] 2015-03-23 23:53
(I edited your comment to put the file in monospaced font).

**Comment by pfrstg** [comment] 2015-03-23 23:53
Thanks -- I was just trying to do that :-)

**Comment by molecule** [comment] 2015-03-23 23:54
Who is this? What are you trying to do? Are you sure you meant to contact
@molecule?

**Comment by rmcgibbo** [comment] 2015-03-23 23:54
lololololol

**Comment by rmcgibbo** [comment] 2015-03-23 23:54
sorry @molecule.

**Comment by rmcgibbo** [comment] 2015-03-23 23:56
@pfrstg, you don't actually want to read the information in the status bit right? The problem is just that it's crashing the reader, I assume, not that this bit contains important information that you want to retain?

**Comment by molecule** [comment] 2015-03-23 23:57
Please remove me from this thread.

**Comment by pfrstg** [comment] 2015-03-23 23:58
That is correct -- I do NOT need the status bits.

**Comment by rmcgibbo** [comment] 2015-03-24 00:01
@molecule: I think you can remove yourself from the right sidebar on github.com, where it says "3 participants", but I don't have the ability to remove you.

**Comment by rmcgibbo** [comment] 2015-03-24 00:09
IIRC @kyleabeauchamp wrote this code. I think the most straightforward thing would be to use a regex to clear the status bit before calling `pd.read_table`, but I don't have a strong preference.

If `pd.read_table` is doing more harm than good, we could obviously iterate over the lines with a regex. My vote is for whichever people feel is simplest.

**Comment by kyleabeauchamp** [comment] 2015-03-24 00:15
@swails might have a better parser in parmed.

**Comment by rmcgibbo** [comment] 2015-03-24 00:37
The ParmEd code here: is https://github.com/ParmEd/ParmEd/blob/fad5e6d4e25bd92c5096b7ef0cc0f442087e16dc/chemistry/formats/mol2.py

IMO, it looks easier to just adopt the band-aid fix of filtering out the status bit.

**Comment by swails** [comment] 2015-03-24 00:38
I can port the code if there's interest.

**Comment by pfrstg** [comment] 2015-03-24 14:03
I'll put together a PR to do the regex filtering.

**Comment by rmcgibbo** [comment] 2015-03-31 21:40
Fixed by #778

**Closed by rmcgibbo** 2015-03-31 21:40 UTC
